name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install dependencies in the 'app/' directory
      - name: Install dependencies
        working-directory: ./app
        run: npm install --package-lock-only  # Generates the package-lock.json

      # Run npm ci and build in the 'app/' directory
      - name: Build the React app
        working-directory: ./app
        run: npm ci && npm run build

      # Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_HERALD_9C3C1 }}
          channelId: live
          projectId: herald-9c3c1
